create table if not exists public.disponibilidades (
 id bigint generated by default as identity primary key,
 created_at timestamptz not null default now(),
 nome text not null,
 whatsapp text not null,
 regiao text not null,
 local text not null,
 dias text not null,
 horarios text not null,
 horario_especifico text,
 observacoes text
);

alter table public.disponibilidades enable row level security;

-- O formulário público pode inserir cadastros.
create policy "cadastro público" on public.disponibilidades
for insert to anon with check (true);

-- NÃO crie SELECT para anon.
-- O painel deve ser protegido por autenticação antes de ser publicado.
